import { Gender, Pagination, TableData } from "./interfaces";

export const mockTableData: TableData[] = [
  {
    id: 1,
    name: "Arianna",
    city: "Berlin",
    email: "arianna@gmail.com",
    age: 32,
    gender: Gender?.Female,
    employee: true,
  },
  {
    id: 2,
    name: "Jacob",
    city: "Madrid",
    email: "jacob@gmail.com",
    age: 39,
    gender: Gender?.PreferNotSay,
    employee: false,
  },
  {
    id: 3,
    name: "Larry",
    city: "London",
    email: "larry@gmail.com",
    age: 50,
    gender: Gender?.Male,
    employee: true,
  },
  {
    id: 4,
    name: "Noelia",
    city: "Tokyo",
    email: "noealia@gmail.com",
    age: 28,
    gender: Gender?.Female,
    employee: true,
  },
];

//
export const mockPaginationData: Pagination = {
  totalProducts: 30,
  products: [
    {
      id: 1,
      name: "Arianna",
      city: "Berlin",
      email: "arianna@gmail.es",
      age: 32,
      gender: Gender.Female,
      employee: true,
      birthDate: "1992-05-15T00:00:00Z",
    },
    {
      id: 2,
      name: "Jacob",
      city: "Madrid",
      email: "jacob@gmail.com",
      age: 39,
      gender: Gender.PreferNotSay,
      employee: false,
      birthDate: "1985-10-20T00:00:00Z",
    },
    {
      id: 3,
      name: "Larry",
      city: "London",
      email: "larry@gmail.com",
      age: 50,
      gender: Gender.Male,
      employee: true,
      birthDate: "1990-03-15T00:00:00Z",
    },
    {
      id: 4,
      name: "Noelia",
      city: "Tokyo",
      email: "noelia@gmail.com",
      age: 28,
      gender: Gender.Female,
      employee: true,
      birthDate: "1978-07-25T00:00:00Z",
    },
    {
      id: 5,
      name: "Carlos",
      city: "Barcelona",
      email: "carlos@gmail.com",
      age: 45,
      gender: Gender.Male,
      employee: false,
      birthDate: "",
    },
    {
      id: 6,
      name: "Emily",
      city: "New York",
      email: "emily@gmail.com",
      age: 29,
      gender: Gender.PreferNotSay,
      employee: true,
      birthDate: "2001-12-05T00:00:00Z",
    },
    {
      id: 7,
      name: "Michael",
      city: "Los Angeles",
      email: "michael@gmail.com",
      age: 35,
      gender: Gender.Male,
      employee: true,
      birthDate: "1995-02-28T00:00:00Z",
    },
    {
      id: 8,
      name: "Sophie",
      city: "Paris",
      email: "sophie@gmail.com",
      age: 31,
      gender: Gender.Female,
      employee: false,
      birthDate: "1990-03-15T00:00:00Z",
    },
    {
      id: 9,
      name: "David",
      city: "Toronto",
      email: "david@gmail.com",
      age: 42,
      gender: Gender.PreferNotSay,
      employee: true,
      birthDate: "1983-11-18T00:00:00Z",
    },
    {
      id: 10,
      name: "Elena",
      city: "Rome",
      email: "elena@gmail.com",
      age: 27,
      gender: Gender.Female,
      employee: false,
      birthDate: "",
    },
    {
      id: 11,
      name: "Marco",
      city: "Milan",
      email: "marco@gmail.com",
      age: 34,
      gender: Gender.Male,
      employee: true,
      birthDate: "1976-04-30T00:00:00Z",
    },
    {
      id: 12,
      name: "Isabella",
      city: "Sydney",
      email: "isabella@gmail.com",
      age: 31,
      gender: Gender.PreferNotSay,
      employee: false,
      birthDate: "1999-08-12T00:00:00Z",
    },
    {
      id: 13,
      name: "Juan",
      city: "Mexico City",
      email: "juan@gmail.com",
      age: 36,
      gender: Gender.Male,
      employee: true,
      birthDate: "2005-06-22T00:00:00Z",
    },
    {
      id: 14,
      name: "Sara",
      city: "Stockholm",
      email: "sara@gmail.com",
      age: 29,
      gender: Gender.Female,
      employee: true,
      birthDate: "1983-11-18T00:00:00Z",
    },
    {
      id: 15,
      name: "Gabriel",
      city: "Sao Paulo",
      email: "gabriel@gmail.com",
      age: 40,
      gender: Gender.Male,
      employee: false,
      birthDate: "1985-10-20T00:00:00Z",
    },
    {
      id: 16,
      name: "Emma",
      city: "Toronto",
      email: "emma@gmail.com",
      age: 25,
      gender: Gender.Female,
      employee: true,
      birthDate: "1990-03-15T00:00:00Z",
    },
    {
      id: 17,
      name: "Andreas",
      city: "Athens",
      email: "andreas@gmail.com",
      age: 33,
      gender: Gender.Male,
      employee: true,
      birthDate: "1978-07-25T00:00:00Z",
    },
    {
      id: 18,
      name: "Mia",
      city: "Amsterdam",
      email: "mia@gmail.com",
      age: 27,
      gender: Gender.Female,
      employee: false,
      birthDate: "2001-12-05T00:00:00Z",
    },
    {
      id: 19,
      name: "Lucas",
      city: "Berlin",
      email: "lucas@gmail.com",
      age: 38,
      gender: Gender.Male,
      employee: true,
      birthDate: "1987-09-10T00:00:00Z",
    },
    {
      id: 20,
      name: "Sophia",
      city: "Paris",
      email: "sophia@gmail.com",
      age: 26,
      gender: Gender.Female,
      employee: false,
      birthDate: "1995-02-28T00:00:00Z",
    },
    {
      id: 21,
      name: "Fernando",
      city: "Lisbon",
      email: "fernando@gmail.com",
      age: 43,
      gender: Gender.Male,
      employee: true,
      birthDate: "1983-11-18T00:00:00Z",
    },
    {
      id: 22,
      name: "Olivia",
      city: "London",
      email: "olivia@gmail.com",
      age: 30,
      gender: Gender.Female,
      employee: true,
      birthDate: "1976-04-30T00:00:00Z",
    },
    {
      id: 23,
      name: "Matteo",
      city: "Florence",
      email: "matteo@gmail.com",
      age: 37,
      gender: Gender.Male,
      employee: false,
      birthDate: "2005-06-22T00:00:00Z",
    },
    {
      id: 24,
      name: "Luna",
      city: "Barcelona",
      email: "luna@gmail.com",
      age: 28,
      gender: Gender.Female,
      employee: true,
      birthDate: "",
    },
    {
      id: 25,
      name: "Diego",
      city: "Buenos Aires",
      email: "diego@gmail.com",
      age: 39,
      gender: Gender.Male,
      employee: true,
      birthDate: "20012-07-22T00:00:00Z",
    },
    {
      id: 26,
      name: "Valentina",
      city: "Santiago",
      email: "valentina@gmail.com",
      age: 32,
      gender: Gender.Female,
      employee: false,
      birthDate: "2005-06-22T00:00:00Z",
    },
    {
      id: 27,
      name: "Sebastian",
      city: "Vienna",
      email: "sebastian@gmail.com",
      age: 41,
      gender: Gender.Male,
      employee: true,
      birthDate: "",
    },
    {
      id: 28,
      name: "Julia",
      city: "Zurich",
      email: "julia@gmail.com",
      age: 24,
      gender: Gender.Female,
      employee: false,
      birthDate: "2002-06-27T00:00:00Z",
    },
    {
      id: 29,
      name: "Lucia",
      city: "Madrid",
      email: "lucia@gmail.com",
      age: 35,
      gender: Gender.Female,
      employee: true,
      birthDate: "",
    },
    {
      id: 30,
      name: "Hector",
      city: "Seville",
      email: "hector@gmail.com",
      age: 44,
      gender: Gender.Male,
      employee: false,
      birthDate: "1999-08-30T00:00:00Z",
    },
    {
      id: 31,
      name: "Zara",
      city: "Palermo",
      email: "zara@gmail.com",
      age: 34,
      gender: Gender.Female,
      employee: false,
      birthDate: "1992-02-22T00:00:00Z",
    },
  ],
};

// Functions
export interface PaginatedResponse<Pagination> {
  products: Pagination[];
  page: number;
  pageSize: number;
}
